/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sw04_gradle;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

import org.apache.commons.lang3.StringUtils;

public class App {
    
    public String getGreeting() {        
        return "Hello World!";
    }

    public static void main(String[] args) {
        String str = "Das ist ein String!";
        
        System.out.println(new App().getGreeting());

        //Ascii render example
        IRender render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(120).height(20);
        builder.element(new PseudoText("peteral2"));
        ICanvas canvas = render.render(builder.build());
        String s = canvas.getText();
        System.out.println(s);


        //StringUtils example
        if (StringUtils.isEmpty(str)) {
            System.out.println("String is empty.");
        } else {
            System.out.println("String is not empty.");
        }
    }
    

}
